### ISSUE TITLE
Move extjs from media/lizard_portal/extjs to media/extjs

### ISSUE THREAD

**Issue by reinout** [lizardsystem/lizard-portal#1]
In lizard-ui (and lizard-map) the external javascript libraries are directly inside media, not inside media/lizard_someting. This makes it easier to exclude extjs from the automatic jslint checking (which is undoubtedly necessary, as it was needed for the other external libraries).

=> move it.

And add a README.extjs file inside the media/ directory with extjs's license in it. Necessary as it otherwise seems like our code.

**Comment by gijs** [comment]
See 6d2a554e017e5e33b19b1f84aa66be2f815a56e0
